from .image_and_mask import NODE_CLASS_MAPPINGS as IMAGE_MASK_MAPPINGS
from .resize_image_or_mask import NODE_CLASS_MAPPINGS as RESIZE_IMAGE_OR_MASK_MAPPINGS
from .logic import NODE_CLASS_MAPPINGS as LOGIC_MAPPINGS
from .ui_control import NODE_CLASS_MAPPINGS as UI_CONTROL_MAPPINGS
from .sampling import NODE_CLASS_MAPPINGS as SAMPLING_MAPPINGS
from .list_processing import NODE_CLASS_MAPPINGS as LIST_PROCESSING_MAPPINGS
from .canvas import NODE_CLASS_MAPPINGS as CANVAS_MAPPINGS
from .reorder_images import NODE_CLASS_MAPPINGS as REORDER_IMAGES_MAPPINGS
from .psd_layer_extract import NODE_CLASS_MAPPINGS as PSD_LAYER_EXTRACT_MAPPINGS
from .image_manager_node import NODE_CLASS_MAPPINGS as IMAGE_MANAGER_MAPPINGS
from .multi_point_gradient import NODE_CLASS_MAPPINGS as MULTI_POINT_GRADIENT_MAPPINGS
from .coordinate_path import NODE_CLASS_MAPPINGS as COORDINATE_PATH_MAPPINGS
from .shape_and_text import NODE_CLASS_MAPPINGS as CREATE_SHAPE_MAPPINGS
from .set_color import NODE_CLASS_MAPPINGS as SET_COLOR_MAPPINGS
from .adjust_image import NODE_CLASS_MAPPINGS as XIS_ADJUST_IMAGE_MAPPINGS
from .shape_data import NODE_CLASS_MAPPINGS as SHAPE_DATA_MAPPINGS
from .curve_editor import NODE_CLASS_MAPPINGS as CURVE_EDITOR_MAPPINGS
from .data_processing import NODE_CLASS_MAPPINGS as PACK_IMAGES_MAPPINGS
from .image_puzzle import NODE_CLASS_MAPPINGS as IMAGE_PUZZLE_MAPPINGS
from .label import NODE_CLASS_MAPPINGS as LABEL_MAPPINGS
from .llm import NODE_CLASS_MAPPINGS as LLM_MAPPINGS

# 合并所有节点的映射
NODE_CLASS_MAPPINGS = {
    **IMAGE_MASK_MAPPINGS,
    **RESIZE_IMAGE_OR_MASK_MAPPINGS,
    **LOGIC_MAPPINGS,
    **UI_CONTROL_MAPPINGS,
    **SAMPLING_MAPPINGS,
    **LIST_PROCESSING_MAPPINGS,
    **CANVAS_MAPPINGS,
    **REORDER_IMAGES_MAPPINGS,
    **PSD_LAYER_EXTRACT_MAPPINGS,
    **IMAGE_MANAGER_MAPPINGS,
    **MULTI_POINT_GRADIENT_MAPPINGS,
    **COORDINATE_PATH_MAPPINGS,
    **CREATE_SHAPE_MAPPINGS,
    **SET_COLOR_MAPPINGS,
    **XIS_ADJUST_IMAGE_MAPPINGS,
    **SHAPE_DATA_MAPPINGS,
    **CURVE_EDITOR_MAPPINGS,
    **PACK_IMAGES_MAPPINGS,
    **IMAGE_PUZZLE_MAPPINGS,
    **LABEL_MAPPINGS,
    **LLM_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    key: cls.__name__.replace("XIS_", "") for key, cls in NODE_CLASS_MAPPINGS.items()
}
